### ISSUE TITLE
axis titles and date ran for benchmarks

### ISSUE THREAD

**Issue by amberisvibin** [Gwion/gwion-docs#6]
The auto-benchmarks do not include axis titles or date ran. I believe the axis titles are very important, and the date ran would be useful. Let me know what you think.

**Comment by fennecdjay** [comment]
You're right.
I think a link to the commit would be nice too.

For now, I'm struggling with GIT-things on the [bench](https://github.com/fennecdjay/gwion-benchmark) repo :confounded:

I guess I'll add it there when CI is in place. But maybe you want to do it? For now it uses gnuplot, but a matplotlib plot could be nice.

**Comment by fennecdjay** [comment]
I'm done with setting up CI for gwion-benchmark.
The only thing that remains to be tested is wether it triggers on a succesful build on gwion master.

Good news, building the doc is now **much** faster :+1:

I should maybe remove the call to trigger the doc from gwion.

I've added date and commit info to the benchmark page, but it still can be improved.

Could you give the page a look? I added a 'yaxis' name, but maybe things can look better.

**Comment by amberisvibin** [comment]
The date and commit info looks good! I don't see the yaxis name.

**Comment by fennecdjay** [comment]
You're right! For some reason I cancelled the build :confused:
Hopefully it'll be there in about half an hour.

**Comment by amberisvibin** [comment]
Okay, thanks!

**Comment by fennecdjay** [comment]
Just figured out I should have open a PR in gwion-benchmark so that you could review :confused:
It the current benchmark script OK now?

Also, I noted that when removing the empty lines between `>` in the benchmark page, it merged the contents (that's what it is supposed to do), so I guess we should provide information for that, e.g.

``` md
Created at:
@hide date

From commit:
@hide git log -n1
```

I suppose it would get us rid of linter warnings and let us preserve formatting.
What do you think?

**Comment by amberisvibin** [comment]
Sorry, I was busy over the weekend. The benchmarks page looks great! That idea of separating the date and commit looks good to me.

**Comment by fennecdjay** [comment]
No problem!
Do you want to do it, or is it ok if I take it (both feel good to me :smile:)?

**Comment by amberisvibin** [comment]
I'll handle it real quick.

**Comment by amberisvibin** [comment]
Okay, I made the PR. #8

**Comment by fennecdjay** [comment]
Nice!
